version: '2'
services:
  jinni-app:
    image: jinni
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jinni-postgresql:5432/jinni
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jinni-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jinni-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8445:8445
  jinni-postgresql:
    extends:
      file: postgresql.yml
      service: jinni-postgresql
  jinni-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jinni-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
